vocabber-ui/src/main/java/kz/vocabber/ui/FeedbackBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.VocabberService;
import kz.vocabber.api.dto.FeedbackDTO;
import kz.vocabber.api.exception.VocabberException;
import kz.vocabber.ui.service.LocalizationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;

/**
 * @author Talgat_Abdulin
 */
@Component
@Lazy
@Scope("request")
public class FeedbackBean {
    private static final Logger logger = LoggerFactory.getLogger(FeedbackBean.class);

    @Resource
    private VocabberService vocabberService;
    @Resource
    private LocalizationService localizationService;
    @Resource
    private UserService userService;

    private FeedbackDTO feedback = new FeedbackDTO();

    public FeedbackDTO getFeedback() {
        return feedback;
    }

    public boolean isEmailRendered() {
        return  userService.getUserEmail() == null;
    }

    public void send() {
        try {
            logger.debug("Sending feedback ({}): \n{}", feedback.getEmail(), feedback.getContent());
            if (!isEmailRendered()) {
                feedback.setEmail(userService.getUserEmail());
            } else if (feedback.getEmail() != null) {
                // TODO: update email
            }

            vocabberService.sendFeedback(feedback);
            reset();
            localizationService.info("feedback.info.thanks");
        } catch (VocabberException e) {
            localizationService.error(e);
        }
    }

    public void cancel() {
        reset();
    }

    public void reset() {
        feedback = new FeedbackDTO();
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/FilterBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.VocabberService;
import kz.vocabber.api.dto.TextDTO;
import kz.vocabber.api.dto.WordDTO;
import kz.vocabber.api.word.WordFilterType;
import kz.vocabber.impl.word.WordFilter;
import kz.vocabber.impl.word.WordFilterFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Set;

/**
 * @author tabdulin
 */
@Component
@Scope("view")
public class FilterBean {
    @Resource
    private WordFilterFactory wordFilterFactory;
    @Resource
    private VocabberService vocabberService;
    @Resource
    private UserService userService;
    @Resource
    private MarkerBean markerBean;
    
    private WordFilterType type;
    private WordsDataTableModel words;

    public void init() {
        List<WordFilter> wordFilters = wordFilterFactory.get(Arrays.asList(type));
        Set<String> excludedWords = wordFilters.get(0).getExcludedWords();
        List<WordDTO> wordDTOs = new ArrayList<WordDTO>(excludedWords.size());
        for (String word : excludedWords) {
            WordDTO dto = new WordDTO();
            dto.setWord(word);
            wordDTOs.add(dto);
        }
        
        TextDTO text = new TextDTO();
        text.setWords(wordDTOs);
        words = new WordsDataTableModel(vocabberService, markerBean.canMark(), text, wordDTOs, true);
    }


    public WordsDataTableModel getWords() {
        if (words == null) {
            init();
        }

        return words;
    }

    public WordFilterType getType() {
        return type;
    }

    public void setType(WordFilterType type) {
        this.type = type;
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/FilterFormBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.word.WordFilterType;
import kz.vocabber.api.word.WordFilterTypeService;
import kz.vocabber.ui.filter.WordFilterTypeItem;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.List;

/**
 * @author tabdulin
 */
@Component
@Scope("view")
public class FilterFormBean {
    private static final Logger logger = LoggerFactory.getLogger(FilterFormBean.class);

    @Resource
    private UserService userService;
    @Resource
    private WordFilterTypeService wordFilterTypeService;

    private List<WordFilterTypeItem> filters;

    @PostConstruct
    public void init() {
        logger.debug("Initializing filterFormBean");
        filters = new ArrayList<WordFilterTypeItem>();
        for (WordFilterType filter : wordFilterTypeService.get()) {
            filters.add(new WordFilterTypeItem(filter, false));
        }
        logger.debug("filterFormBean were initialized");
    }

    public List<WordFilterTypeItem> getFilters() {
        return filters;
    }

    public List<WordFilterType> getSelectedFilters() {
        List<WordFilterType> selected = new ArrayList<WordFilterType>(filters.size());
        for (WordFilterTypeItem filterItem : filters) {
            if (filterItem.isSelected()) {
                selected.add(filterItem.getFilter());
            }
        }
        return selected;
    }

    public void setSelectedFilters(List<WordFilterType> selectedFilters) {
        for (WordFilterTypeItem filterItem : filters) {
            filterItem.setSelected(false);
            if (selectedFilters != null && selectedFilters.contains(filterItem.getFilter())) {
                filterItem.setSelected(true);
            }
        }
    }

    public void reset() {
        setSelectedFilters(null);
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/MarkerBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.VocabberService;
import kz.vocabber.api.dto.WordTranslationDTO;
import kz.vocabber.api.exception.VocabberException;
import kz.vocabber.db.model.user.UserWord;
import kz.vocabber.impl.users.UserRole;
import kz.vocabber.ui.service.LocalizationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.util.List;

/**
 * @author tabdulin
 */
@Component
public class MarkerBean {
    private static final Logger logger = LoggerFactory.getLogger(MarkerBean.class);

    @Resource
    private LocalizationService localizationService;
    @Resource
    private VocabberService vocabberService;
    @Resource
    private UserService userService;

    public boolean canMark() {
        return userService.getCurrentUser().getRole() == UserRole.ROLE_USER;
    }

    public boolean canRemember(UserWord.Status status) {
        return canMark() && status != UserWord.Status.learnt;
    }

    public boolean canForget(UserWord.Status status) {
        return canMark() && status == UserWord.Status.learnt;
    }

    public String forget(WordTranslationDTO word) {
        try {
            vocabberService.forget(word);
            return localizationService.info("info.word.forgot", word.getWord());
        } catch (VocabberException e) {
            return localizationService.error(e);
        }
    }

    public String remember(WordTranslationDTO words) {
        try {
            vocabberService.remember(words);
            return localizationService.info("info.word.remembered", words.getWord());
        } catch (VocabberException e) {
            return localizationService.error(e);
        }
    }

    public String rememberPage(List<WordTranslationDTO> words) {
        try {
            vocabberService.remember(words.toArray(new WordTranslationDTO[words.size()]));
            return localizationService.info("info.word.page.remembered");
        } catch (VocabberException e) {
            return localizationService.error(e);
        }
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/TemplateBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.dto.UserDTO;
import kz.vocabber.impl.users.UserRole;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;

/**
 * @author Talgat_Abdulin
 */
@Component
public class TemplateBean {
    @Resource
    private UserService userService;

    public boolean isLoginRendered() {
        return userService.getCurrentUser().getRole() == UserRole.ROLE_ANONYMOUS;
    }
    
    public UserDTO getUser() {
        return userService.getCurrentUser();
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/TextFormBean.java
package kz.vocabber.ui;

import kz.vocabber.api.file.FileType;
import kz.vocabber.api.file.FileTypeService;
import org.primefaces.model.UploadedFile;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import java.util.List;

/**
 * @author tabdulin
 */
@Component
@Scope("view")
public class TextFormBean {
    @Resource
    private FileTypeService fileTypeService;

    private UploadedFile file;
    private String text;
    private String link;

    @PostConstruct
    public void reset() {
        file = null;
        text = null;
        link = null;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public UploadedFile getFile() {
        return file;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    public List<FileType> getFileTypes() {
        return fileTypeService.getUploadable();
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/TextHistoryBean.java
package kz.vocabber.ui;

import kz.vocabber.api.VocabberService;
import kz.vocabber.api.comparator.TextDateComparator;
import kz.vocabber.api.dto.TextDTO;
import kz.vocabber.api.exception.VocabberException;
import kz.vocabber.ui.service.LocalizationService;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import java.util.Collections;
import java.util.List;

/**
 * @author Talgat_Abdulin
 */
@Component
@Scope("view")
public class TextHistoryBean {
    @Resource
    private VocabberService vocabberService;
    @Resource
    private LocalizationService localizationService;
    @Resource
    private TextHashIdConverter textHashIdConverter;

    private List<TextDTO> texts;

    @PostConstruct
    public void init() {
        try {
            texts = vocabberService.getHistory();

            Collections.sort(texts, new TextDateComparator(false));
        } catch (VocabberException e) {
            localizationService.error(e);
        }
    }

    public String load(TextDTO text) {
        return "/ui/words.jsf?faces-redirect=true&id=" +
                textHashIdConverter.toString(text.getId(), text.getHash());
    }
    
    public List<TextDTO> getTexts() {
        return texts;
    }

    public void setTexts(List<TextDTO> texts) {
        this.texts = texts;
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/TextUploadBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.VocabberService;
import kz.vocabber.api.dto.FileDTO;
import kz.vocabber.api.dto.TextDTO;
import kz.vocabber.api.exception.VocabberException;
import kz.vocabber.ui.menu.MenuBean;
import kz.vocabber.ui.menu.MenuItem;
import kz.vocabber.ui.service.LocalizationService;
import kz.vocabber.ui.service.SessionMapService;
import kz.vocabber.ui.service.UrlService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.io.IOException;

/**
 * @author tabdulin
 */
@Component
@Scope("view")
public class TextUploadBean {
    private static final Logger logger = LoggerFactory.getLogger(TextUploadBean.class);

    @Resource
    private TextFormBean textForm;
    @Resource
    private FilterFormBean filterForm;
    @Resource
    private MarkerBean markerBean;

    @Resource
    private MenuBean menuBean;
    @Resource
    private UrlService urlService;
    @Resource
    private LocalizationService localizationService;
    @Resource
    private SessionMapService sessionMapService;
    @Resource
    private VocabberService vocabberService;
    @Resource
    private UserService userService;
    @Resource
    private TextHashIdConverter textHashIdConverter;

    public String upload() {
        TextDTO text = null;
        if (menuBean.getActive() == MenuItem.FILE) {
            try {
                FileDTO fileDTO = new FileDTO();
                fileDTO.setSize(textForm.getFile().getSize());
                fileDTO.setName(textForm.getFile().getFileName());
                fileDTO.setMime(textForm.getFile().getContentType());
                fileDTO.setStream(textForm.getFile().getInputstream());
                text = vocabberService.parseFile(fileDTO);
            } catch (IOException e) {
                return localizationService.error("error.file.upload", textForm.getFile().getFileName());
            } catch (VocabberException e) {
                return localizationService.error(e);
            }
        }

        if (menuBean.getActive() == MenuItem.TEXT) {
            try {
                text = vocabberService.parseText(textForm.getText());
            } catch (VocabberException e) {
                return localizationService.error(e);
            }
        }

        if (menuBean.getActive() == MenuItem.LINK) {
            try {
                text = vocabberService.parseWebPage(textForm.getLink());
            } catch (VocabberException e) {
                return localizationService.error(e);
            }
        }

        sessionMapService.add(SessionMapService.FILTERS_PREFIX + text.getId(), filterForm.getSelectedFilters());
        return "/ui/words.jsf?faces-redirect=true&id=" + textHashIdConverter.toString(text.getId(), text.getHash());
    }

    public String reset() {
        textForm.reset();
        filterForm.reset();
        return "?faces-redirect=true";
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/WordsBean.java
package kz.vocabber.ui;

import kz.vocabber.api.VocabberService;
import kz.vocabber.api.dto.TextDTO;
import kz.vocabber.api.dto.WordDTO;
import kz.vocabber.api.exception.VocabberException;
import kz.vocabber.api.word.WordFilterType;
import kz.vocabber.ui.filter.WordFilterTypeListConverter;
import kz.vocabber.ui.service.LocalizationService;
import kz.vocabber.ui.service.SessionMapService;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.util.List;

/**
 * @author Talgat_Abdulin
 */
@Component
@Scope("view")
public class WordsBean {
    private TextHashId hashId;
    private WordsDataTableModel words;

    @Resource
    private VocabberService vocabberService;
    @Resource
    private LocalizationService localizationService;
    @Resource
    private SessionMapService sessionMapService;
    @Resource
    private MarkerBean markerBean;
    @Resource
    private FilterFormBean filterForm;
    @Resource
    private WordFilterTypeListConverter wordFilterTypeListConverter;
    @Resource
    private TextHashIdConverter textHashIdConverter;

    private void init() {
        try {
            List<WordFilterType> selectedFilters = (List<WordFilterType>) sessionMapService
                    .getAndRemove(SessionMapService.FILTERS_PREFIX + hashId);
            if (selectedFilters != null) {
                filterForm.setSelectedFilters(selectedFilters);
            }

            TextDTO text = vocabberService.getText(hashId.getId(), hashId.getHash());
            List<WordDTO> filteredWords = vocabberService.filter(text.getWords(), filterForm.getSelectedFilters());
            words = new WordsDataTableModel(vocabberService, markerBean.canMark(),
                    text, filteredWords, false);
        } catch (VocabberException e) {
            localizationService.error(e);
        }
    }

    public TextHashId getHashId() {
        return hashId;
    }

    public void setHashId(TextHashId hashId) {
        this.hashId = hashId;

        if (words == null && hashId != null) {
            init();
        }
    }
    
    public WordsDataTableModel getWords() {
        return words;
    }

    public void filter() {
        try {
            List<WordDTO> filteredWords = vocabberService.filter(words.getText().getWords(),
                    filterForm.getSelectedFilters());
            words.setWords(filteredWords);
        } catch (VocabberException e) {
            localizationService.error(e);
        }
    }
    
    public String print() {
        return "print.jsf?faces-redirect=true&id=" + textHashIdConverter.toString(hashId) + "&filters="
                + wordFilterTypeListConverter.toString(filterForm.getSelectedFilters());
    }
}

vocabber-ui/src/main/webapp/ui/upload/file.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/ui/upload/upload.xhtml">
    <ui:define name="form">
        <div class="file">
            <div class="filetypes">
                <p>#{i18n['info.main']}</p>
                <p>
                    #{i18n['info.file']}
                    <ui:repeat value="#{textFormBean.fileTypes}"
                               var="fileType" varStatus="status">
                        <span class="filetype">#{fileType.extension}<h:outputText value="#{not status.last ? ',' : '.' }"/></span>
                    </ui:repeat>
                </p>
            </div>
            <p:fileUpload value="#{textFormBean.file}"
                          mode="simple"
                          styleClass="upload"/>
        </div>
    </ui:define>
</ui:composition>

vocabber-ui/src/main/webapp/ui/upload/history.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/css/templates/equivalency/equivalency.xhtml">

    <ui:define name="head">
        <title>#{i18n['page.history.title']}</title>
    </ui:define>
    <ui:define name="content">
        <div class="history-page">
            <div class="history-info">
                <p class="details">
                    Ниже перечислены ваши загруженные тексты.
                    При клике на название текста вы перейдете на страницу со словами загруженного текста.
                </p>
            </div>
            <h:form id="vocabber" enctype="multipart/form-data" prependId="true">
                <p:dataTable id="texts" value="#{textHistoryBean.texts}" var="text"
                             styleClass="texts-table"
                             rowStyleClass="texts-row"
                             paginator="true" rows="10"
                             paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             paginatorAlwaysVisible="false"
                             rowsPerPageTemplate="10,30,50"
                             emptyMessage="#{i18n['history.empty']}"
                             rendered="#{not empty textHistoryBean.texts}">
                    <p:column headerText="#{i18n['history.text.date']}"
                              styleClass="date">
                        <h:outputText value="#{text.date}">
                            <f:convertDateTime pattern="yyyy-MM-dd"/>
                        </h:outputText>
                    </p:column>

                    <p:column headerText="#{i18n['history.text.title']}"
                              styleClass="title">
                        <p:commandLink action="#{textHistoryBean.load(text)}"
                                styleClass="load"
                                immediate="true"
                                ajax="false">
                            #{text.title}
                        </p:commandLink>
                    </p:column>
                </p:dataTable>
            </h:form>
        </div>
    </ui:define>
</ui:composition>

vocabber-ui/src/main/webapp/ui/upload/link.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/ui/upload/upload.xhtml">
    <ui:define name="form">
        <div class="link">
            <div class="info">#{i18n['info.link']}</div>
            <p:inputText value="#{textFormBean.link}"
                         styleClass="field"/>
            <div class="info detailed">
                <div>#{i18n['info.link.detailed.1']}</div>
                <ul>
                    <li class="example">http://en.wikipedia.org</li>
                    <li class="example">http://news.google.com</li>
                </ul>
                <div>#{i18n['info.link.detailed.2']}</div>
            </div>
        </div>
    </ui:define>
</ui:composition>

vocabber-ui/src/main/webapp/ui/upload/text.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/ui/upload/upload.xhtml">
    <ui:define name="form">
        <div class="text">
            <div>#{i18n['info.text']}</div>
            <p:inputTextarea value="#{textFormBean.text}" styleClass="field"
                             autoResize="false" />
        </div>
    </ui:define>
</ui:composition>

vocabber-ui/src/main/webapp/ui/upload/upload.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/css/templates/equivalency/equivalency.xhtml">

    <ui:define name="head">
        <title>#{i18n['page.main.title']}</title>
    </ui:define>
    <ui:define name="content">
        <div class="processor-page">
            <h:form id="vocabber" enctype="multipart/form-data" prependId="true">
                <div class="layout">
                    <div class="layout-left">
                        <div class="text-form">
                            <ui:insert name="form"/>
                        </div>
                    </div>

                    <div class="layout-right">
                        <ui:include src="/ui/common/filters.xhtml"/>
                    </div>
                </div>

                <div class="buttons">
                    <p:commandButton id="process" value="#{i18n['button.process']}"
                                     action="#{textUploadBean.upload}"
                                     ajax="false"/>
                    <p:commandButton id="reset" value="#{i18n['button.reset']}"
                                     action="#{textUploadBean.reset}"
                                     ajax="false"/>
                </div>
            </h:form>
        </div>
    </ui:define>
</ui:composition>