vocabber-ui/src/main/java/kz/vocabber/ui/FeedbackBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.VocabberService;
import kz.vocabber.api.dto.FeedbackDTO;
import kz.vocabber.api.exception.VocabberException;
import kz.vocabber.ui.service.LocalizationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;

/**
 * @author Talgat_Abdulin
 */
@Component
@Lazy
@Scope("request")
public class FeedbackBean {
    private static final Logger logger = LoggerFactory.getLogger(FeedbackBean.class);

    @Resource
    private VocabberService vocabberService;
    @Resource
    private LocalizationService localizationService;
    @Resource
    private UserService userService;

    private FeedbackDTO feedback = new FeedbackDTO();

    public FeedbackDTO getFeedback() {
        return feedback;
    }

    public boolean isEmailRendered() {
        return  userService.getUserEmail() == null;
    }

    public void send() {
        try {
            logger.debug("Sending feedback ({}): \n{}", feedback.getEmail(), feedback.getContent());
            if (!isEmailRendered()) {
                feedback.setEmail(userService.getUserEmail());
            } else if (feedback.getEmail() != null) {
                // TODO: update email
            }

            vocabberService.sendFeedback(feedback);
            reset();
            localizationService.info("feedback.info.thanks");
        } catch (VocabberException e) {
            localizationService.error(e);
        }
    }

    public void cancel() {
        reset();
    }

    public void reset() {
        feedback = new FeedbackDTO();
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/FilterBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.VocabberService;
import kz.vocabber.api.dto.TextDTO;
import kz.vocabber.api.dto.WordDTO;
import kz.vocabber.api.word.WordFilterType;
import kz.vocabber.impl.word.WordFilter;
import kz.vocabber.impl.word.WordFilterFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Set;

/**
 * @author tabdulin
 */
@Component
@Scope("view")
public class FilterBean {
    @Resource
    private WordFilterFactory wordFilterFactory;
    @Resource
    private VocabberService vocabberService;
    @Resource
    private UserService userService;
    @Resource
    private MarkerBean markerBean;
    
    private WordFilterType type;
    private WordsDataTableModel words;

    public void init() {
        List<WordFilter> wordFilters = wordFilterFactory.get(Arrays.asList(type));
        Set<String> excludedWords = wordFilters.get(0).getExcludedWords();
        List<WordDTO> wordDTOs = new ArrayList<WordDTO>(excludedWords.size());
        for (String word : excludedWords) {
            WordDTO dto = new WordDTO();
            dto.setWord(word);
            wordDTOs.add(dto);
        }
        
        TextDTO text = new TextDTO();
        text.setWords(wordDTOs);
        words = new WordsDataTableModel(vocabberService, markerBean.canMark(), text, wordDTOs, true);
    }


    public WordsDataTableModel getWords() {
        if (words == null) {
            init();
        }

        return words;
    }

    public WordFilterType getType() {
        return type;
    }

    public void setType(WordFilterType type) {
        this.type = type;
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/FilterFormBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.word.WordFilterType;
import kz.vocabber.api.word.WordFilterTypeService;
import kz.vocabber.ui.filter.WordFilterTypeItem;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.List;

/**
 * @author tabdulin
 */
@Component
@Scope("view")
public class FilterFormBean {
    private static final Logger logger = LoggerFactory.getLogger(FilterFormBean.class);

    @Resource
    private UserService userService;
    @Resource
    private WordFilterTypeService wordFilterTypeService;

    private List<WordFilterTypeItem> filters;

    @PostConstruct
    public void init() {
        logger.debug("Initializing filterFormBean");
        filters = new ArrayList<WordFilterTypeItem>();
        for (WordFilterType filter : wordFilterTypeService.get()) {
            filters.add(new WordFilterTypeItem(filter, false));
        }
        logger.debug("filterFormBean were initialized");
    }

    public List<WordFilterTypeItem> getFilters() {
        return filters;
    }

    public List<WordFilterType> getSelectedFilters() {
        List<WordFilterType> selected = new ArrayList<WordFilterType>(filters.size());
        for (WordFilterTypeItem filterItem : filters) {
            if (filterItem.isSelected()) {
                selected.add(filterItem.getFilter());
            }
        }
        return selected;
    }

    public void setSelectedFilters(List<WordFilterType> selectedFilters) {
        for (WordFilterTypeItem filterItem : filters) {
            filterItem.setSelected(false);
            if (selectedFilters != null && selectedFilters.contains(filterItem.getFilter())) {
                filterItem.setSelected(true);
            }
        }
    }

    public void reset() {
        setSelectedFilters(null);
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/MarkerBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.VocabberService;
import kz.vocabber.api.dto.WordTranslationDTO;
import kz.vocabber.api.exception.VocabberException;
import kz.vocabber.db.model.user.UserWord;
import kz.vocabber.impl.users.UserRole;
import kz.vocabber.ui.service.LocalizationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.util.List;

/**
 * @author tabdulin
 */
@Component
public class MarkerBean {
    private static final Logger logger = LoggerFactory.getLogger(MarkerBean.class);

    @Resource
    private LocalizationService localizationService;
    @Resource
    private VocabberService vocabberService;
    @Resource
    private UserService userService;

    public boolean canMark() {
        return userService.getCurrentUser().getRole() == UserRole.ROLE_USER;
    }

    public boolean canRemember(UserWord.Status status) {
        return canMark() && status != UserWord.Status.learnt;
    }

    public boolean canForget(UserWord.Status status) {
        return canMark() && status == UserWord.Status.learnt;
    }

    public String forget(WordTranslationDTO word) {
        try {
            vocabberService.forget(word);
            return localizationService.info("info.word.forgot", word.getWord());
        } catch (VocabberException e) {
            return localizationService.error(e);
        }
    }

    public String remember(WordTranslationDTO words) {
        try {
            vocabberService.remember(words);
            return localizationService.info("info.word.remembered", words.getWord());
        } catch (VocabberException e) {
            return localizationService.error(e);
        }
    }

    public String rememberPage(List<WordTranslationDTO> words) {
        try {
            vocabberService.remember(words.toArray(new WordTranslationDTO[words.size()]));
            return localizationService.info("info.word.page.remembered");
        } catch (VocabberException e) {
            return localizationService.error(e);
        }
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/TemplateBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.dto.UserDTO;
import kz.vocabber.impl.users.UserRole;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;

/**
 * @author Talgat_Abdulin
 */
@Component
public class TemplateBean {
    @Resource
    private UserService userService;

    public boolean isLoginRendered() {
        return userService.getCurrentUser().getRole() == UserRole.ROLE_ANONYMOUS;
    }
    
    public UserDTO getUser() {
        return userService.getCurrentUser();
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/TextFormBean.java
package kz.vocabber.ui;

import kz.vocabber.api.file.FileType;
import kz.vocabber.api.file.FileTypeService;
import org.primefaces.model.UploadedFile;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import java.util.List;

/**
 * @author tabdulin
 */
@Component
@Scope("view")
public class TextFormBean {
    @Resource
    private FileTypeService fileTypeService;

    private UploadedFile file;
    private String text;
    private String link;

    @PostConstruct
    public void reset() {
        file = null;
        text = null;
        link = null;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public UploadedFile getFile() {
        return file;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    public List<FileType> getFileTypes() {
        return fileTypeService.getUploadable();
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/TextHistoryBean.java
package kz.vocabber.ui;

import kz.vocabber.api.VocabberService;
import kz.vocabber.api.comparator.TextDateComparator;
import kz.vocabber.api.dto.TextDTO;
import kz.vocabber.api.exception.VocabberException;
import kz.vocabber.ui.service.LocalizationService;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import java.util.Collections;
import java.util.List;

/**
 * @author Talgat_Abdulin
 */
@Component
@Scope("view")
public class TextHistoryBean {
    @Resource
    private VocabberService vocabberService;
    @Resource
    private LocalizationService localizationService;
    @Resource
    private TextHashIdConverter textHashIdConverter;

    private List<TextDTO> texts;

    @PostConstruct
    public void init() {
        try {
            texts = vocabberService.getHistory();

            Collections.sort(texts, new TextDateComparator(false));
        } catch (VocabberException e) {
            localizationService.error(e);
        }
    }

    public String load(TextDTO text) {
        return "/ui/words.jsf?faces-redirect=true&id=" +
                textHashIdConverter.toString(text.getId(), text.getHash());
    }
    
    public List<TextDTO> getTexts() {
        return texts;
    }

    public void setTexts(List<TextDTO> texts) {
        this.texts = texts;
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/TextUploadBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.VocabberService;
import kz.vocabber.api.dto.FileDTO;
import kz.vocabber.api.dto.TextDTO;
import kz.vocabber.api.exception.VocabberException;
import kz.vocabber.ui.menu.MenuBean;
import kz.vocabber.ui.menu.MenuItem;
import kz.vocabber.ui.service.LocalizationService;
import kz.vocabber.ui.service.SessionMapService;
import kz.vocabber.ui.service.UrlService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.io.IOException;

/**
 * @author tabdulin
 */
@Component
@Scope("view")
public class TextUploadBean {
    private static final Logger logger = LoggerFactory.getLogger(TextUploadBean.class);

    @Resource
    private TextFormBean textForm;
    @Resource
    private FilterFormBean filterForm;
    @Resource
    private MarkerBean markerBean;

    @Resource
    private MenuBean menuBean;
    @Resource
    private UrlService urlService;
    @Resource
    private LocalizationService localizationService;
    @Resource
    private SessionMapService sessionMapService;
    @Resource
    private VocabberService vocabberService;
    @Resource
    private UserService userService;
    @Resource
    private TextHashIdConverter textHashIdConverter;

    public String upload() {
        TextDTO text = null;
        if (menuBean.getActive() == MenuItem.FILE) {
            try {
                FileDTO fileDTO = new FileDTO();
                fileDTO.setSize(textForm.getFile().getSize());
                fileDTO.setName(textForm.getFile().getFileName());
                fileDTO.setMime(textForm.getFile().getContentType());
                fileDTO.setStream(textForm.getFile().getInputstream());
                text = vocabberService.parseFile(fileDTO);
            } catch (IOException e) {
                return localizationService.error("error.file.upload", textForm.getFile().getFileName());
            } catch (VocabberException e) {
                return localizationService.error(e);
            }
        }

        if (menuBean.getActive() == MenuItem.TEXT) {
            try {
                text = vocabberService.parseText(textForm.getText());
            } catch (VocabberException e) {
                return localizationService.error(e);
            }
        }

        if (menuBean.getActive() == MenuItem.LINK) {
            try {
                text = vocabberService.parseWebPage(textForm.getLink());
            } catch (VocabberException e) {
                return localizationService.error(e);
            }
        }

        sessionMapService.add(SessionMapService.FILTERS_PREFIX + text.getId(), filterForm.getSelectedFilters());
        return "/ui/words.jsf?faces-redirect=true&id=" + textHashIdConverter.toString(text.getId(), text.getHash());
    }

    public String reset() {
        textForm.reset();
        filterForm.reset();
        return "?faces-redirect=true";
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/WordsBean.java
package kz.vocabber.ui;

import kz.vocabber.api.VocabberService;
import kz.vocabber.api.dto.TextDTO;
import kz.vocabber.api.dto.WordDTO;
import kz.vocabber.api.exception.VocabberException;
import kz.vocabber.api.word.WordFilterType;
import kz.vocabber.ui.filter.WordFilterTypeListConverter;
import kz.vocabber.ui.service.LocalizationService;
import kz.vocabber.ui.service.SessionMapService;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.util.List;

/**
 * @author Talgat_Abdulin
 */
@Component
@Scope("view")
public class WordsBean {
    private TextHashId hashId;
    private WordsDataTableModel words;

    @Resource
    private VocabberService vocabberService;
    @Resource
    private LocalizationService localizationService;
    @Resource
    private SessionMapService sessionMapService;
    @Resource
    private MarkerBean markerBean;
    @Resource
    private FilterFormBean filterForm;
    @Resource
    private WordFilterTypeListConverter wordFilterTypeListConverter;
    @Resource
    private TextHashIdConverter textHashIdConverter;

    private void init() {
        try {
            List<WordFilterType> selectedFilters = (List<WordFilterType>) sessionMapService
                    .getAndRemove(SessionMapService.FILTERS_PREFIX + hashId);
            if (selectedFilters != null) {
                filterForm.setSelectedFilters(selectedFilters);
            }

            TextDTO text = vocabberService.getText(hashId.getId(), hashId.getHash());
            List<WordDTO> filteredWords = vocabberService.filter(text.getWords(), filterForm.getSelectedFilters());
            words = new WordsDataTableModel(vocabberService, markerBean.canMark(),
                    text, filteredWords, false);
        } catch (VocabberException e) {
            localizationService.error(e);
        }
    }

    public TextHashId getHashId() {
        return hashId;
    }

    public void setHashId(TextHashId hashId) {
        this.hashId = hashId;

        if (words == null && hashId != null) {
            init();
        }
    }
    
    public WordsDataTableModel getWords() {
        return words;
    }

    public void filter() {
        try {
            List<WordDTO> filteredWords = vocabberService.filter(words.getText().getWords(),
                    filterForm.getSelectedFilters());
            words.setWords(filteredWords);
        } catch (VocabberException e) {
            localizationService.error(e);
        }
    }
    
    public String print() {
        return "print.jsf?faces-redirect=true&id=" + textHashIdConverter.toString(hashId) + "&filters="
                + wordFilterTypeListConverter.toString(filterForm.getSelectedFilters());
    }
}

vocabber-ui/src/main/webapp/ui/common/feedback.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">
    <h:form id="feedbackLinkForm">
        <p:commandLink action="#{feedbackBean.reset}"
                       oncomplete="javascript:feedbackDialog.show();"
                       update=":feedbackForm"
                       style="display:scroll;position:fixed;top:40%;left:-5px;"
                       title="#{i18n['feedback.open']}">
            <img src="#{request.contextPath}/css/templates/equivalency/images/feedback.png" alt=""/>
        </p:commandLink>
    </h:form>
       
    <p:dialog id="feedbackDialog" widgetVar="feedbackDialog"
              styleClass="feedback"
            modal="true" header="#{i18n['feedback.header']}"
            draggable="false"
            resizable="false"
            minWidth="600"
            minHeight="300">

        <div class="description">
            #{i18n['feedback.info']}
        </div>
        <h:form id="feedbackForm">
            <p:outputPanel layout="block"
                           styleClass="email"
                           rendered="#{feedbackBean.emailRendered}">
                <p:inputText id="email" styleClass="field"
                             value="#{feedbackBean.feedback.email}"
                             validatorMessage="#{i18n['feedback.error.email.incorrect']}">
                    <f:validateRegex pattern="[\w\.-]*[a-zA-Z0-9_]@[\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]" />
                </p:inputText>
                <label>#{i18n['feedback.email']}</label>
                <span class="info">#{i18n['feedback.email.info']}</span>
            </p:outputPanel>
            <div class="content">
                <p:inputTextarea id="content" styleClass="field"
                                 value="#{feedbackBean.feedback.content}"
                                 required="true"
                                 requiredMessage="#{i18n['feedback.error.content.absent']}"/>
            </div>

            <p:outputPanel id="errors" styleClass="errors">
                <p:message for="email" display="text" styleClass="error"/>
                <p:message for="content" display="text" styleClass="error"/>
            </p:outputPanel>

            <div class="buttons">
                <p:commandButton value="#{i18n['feedback.button.send']}"
                                 action="#{feedbackBean.send}"
                                 oncomplete="handleFeedbackRequest(xhr,status,args);"
                                 update=":messages:growl :feedbackForm"/>
                <p:commandButton value="#{i18n['feedback.button.cancel']}"
                                 action="#{feedbackBean.cancel}"
                                 immediate="true"
                                 onclick="feedbackDialog.hide();"
                                 update=":feedbackForm"/>
            </div>
        </h:form>
    </p:dialog>
    <script type="text/javascript">
        function handleFeedbackRequest(xhr, status, args) {
            if(!args.validationFailed) {
                feedbackDialog.hide();
            }
        }
    </script>
</ui:composition>

vocabber-ui/src/main/webapp/ui/common/filters.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

<div class="filters-form">
    <div class="title">#{i18n['word.filter.title']}</div>

    <ul class="list">
    <ui:repeat value="#{filterFormBean.filters}" var="item">
        <li class="item">
            <p:selectBooleanCheckbox value="#{item.selected}"
                    widgetVar="filterSelector_#{item.filter.value}"/>
            <h:outputText styleClass="label"
                          value="#{i18n[item.filter.code]}"/>
            <a href="filter.jsf?id=#{item.filter.value}"
                title="#{i18n['word.filter.view']}">
                <img src="#{request.contextPath}/css/templates/equivalency/images/onebit_39.png"
                     class="icon" alt="#{i18n['word.filter.view']}"/>
            </a>
        </li>
    </ui:repeat>
    </ul>

    <div class="selectors">
        <script type="text/javascript">
            function filterSelectAll() {
            <ui:repeat value="#{filterFormBean.filters}" var="item">
                filterSelector_#{item.filter.value}.check();
            </ui:repeat>
            };

            function filterSelectNone() {
            <ui:repeat value="#{filterFormBean.filters}" var="item">
                filterSelector_#{item.filter.value}.uncheck();
            </ui:repeat>
            };
        </script>
        <a href="#" onclick="filterSelectAll(); return false;">#{i18n['word.filter.select.all']}</a>
        <a href="#" onclick="filterSelectNone(); return false;">#{i18n['word.filter.select.none']}</a>
    </div>
</div>


</ui:composition>

vocabber-ui/src/main/webapp/ui/common/ga.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-26498953-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</ui:composition>

vocabber-ui/src/main/webapp/ui/common/transcriptions.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">
    <ui:repeat var="transcription" value="#{word.transcriptions}" varStatus="status">
        <div class="transcription">
            #{transcription}
        </div>
    </ui:repeat>

</ui:composition>

vocabber-ui/src/main/webapp/ui/common/translations.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">
    <span class="translations">
    <ui:repeat var="translation" value="#{word.translations}" varStatus="status">
        #{translation}#{not status.last ? '; ' : ''}
    </ui:repeat>
    </span>
</ui:composition>

vocabber-ui/src/main/webapp/ui/common/wordsTable.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <p:outputPanel id="wordsPanel" styleClass="words-panel" layout="block">
        <p:outputPanel id="lettersPanel" styleClass="letters" layout="block"
                rendered="#{table.renderAlphabet()}">
            <ui:repeat value="#{table.letters}" var="letter">
                <p:commandLink action="#{table.changeLetter(letter)}"
                               value="#{letter}"
                               rendered="#{table.hasLetter(letter)}"
                               styleClass="letter #{letter eq table.letter ? 'current' : ''}"
                               update=":vocabber:wordsPanel">
                </p:commandLink>
                <h:outputText value="#{letter}"
                              rendered="#{not table.hasLetter(letter)}"
                              styleClass="letter"/>
            </ui:repeat>
        </p:outputPanel>
        <div style="display:none">
            <!-- TODO: refactor -->
            <p:commandLink action="#{markerBean.rememberPage(table.page)}"
                           id="rememberPageActionBottom"
                           value="#{i18n['button.remember.page']}"
                           title="#{i18n['button.remember.page.tooltip']}"
                           rendered="#{markerBean.canMark()}"
                           styleClass="rememberPageAction"
                           update=":messages:growl :vocabber:wordsPanel">
                <f:setPropertyActionListener target="#{table.caching}" value="#{true}"/>
            </p:commandLink>
            <p:commandLink action="#{markerBean.rememberPage(table.page)}"
                           id="rememberPageActionTop"
                           value="#{i18n['button.remember.page']}"
                           title="#{i18n['button.remember.page.tooltip']}"
                           rendered="#{markerBean.canMark()}"
                           styleClass="rememberPageAction"
                           update=":messages:growl :vocabber:wordsPanel">
                <f:setPropertyActionListener target="#{table.caching}" value="#{true}"/>
            </p:commandLink>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function() {
                jQuery(PrimeFaces.escapeClientId('vocabber:rememberPageActionTop')).insertBefore(
                    jQuery(PrimeFaces.escapeClientId('vocabber:words_paginator_top') + ' .ui-paginator-current'));
                jQuery(PrimeFaces.escapeClientId('vocabber:rememberPageActionBottom')).insertBefore(
                    jQuery(PrimeFaces.escapeClientId('vocabber:words_paginator_bottom') + ' .ui-paginator-current'));
            });
        </script>
        <p:dataTable id="words" widgetVar="words" var="fword" value="#{table}"
                     paginator="true" rows="10"
                     styleClass="words-table #{table.renderStatistics() ? '' : 'no-statistics'}"
                     rowStyleClass="#{fword.status}"
                     paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                     paginatorAlwaysVisible="false"
                     rowsPerPageTemplate="10,30,50"
                     emptyMessage="#{i18n['word.list.empty']}"
                     rendered="#{table != null}"
                     sortBy="#{fword.frequency}"
                     sortOrder="#{sortOrder}">
            <f:facet name="header">
                <span class="statistics">
                    <span class="total">#{i18n['word.list.size']} #{table.wordsProcessed}</span>
                    <span class="filtered">#{i18n['word.list.filtered.size']} #{table.wordsFound - table.wordsProcessed}</span>
                </span>
            </f:facet>

            <p:column headerText="#{i18n['word.text']}"
                      styleClass="word"
                      sortBy="#{fword.word}">
                #{fword.word}
                <span class="actions">
                    <!-- TODO: optimize -->
                    <p:commandLink action="#{markerBean.remember(fword)}"
                                   value="&#160;"
                                   title="#{i18n['button.remember']}"
                                   rendered="#{markerBean.canRemember(fword.status)}"
                                   styleClass="action remember"
                                   update=":messages:growl :vocabber:wordsPanel">
                        <f:setPropertyActionListener target="#{table.caching}" value="#{true}"/>
                    </p:commandLink>
                    <p:commandLink action="#{markerBean.forget(fword)}"
                                   value="&#160;"
                                   title="#{i18n['button.forget']}"
                                   rendered="#{markerBean.canForget(fword.status)}"
                                   styleClass="action forget"
                                   update=":messages:growl :vocabber:wordsPanel">
                        <f:setPropertyActionListener target="#{table.caching}" value="#{true}"/>
                    </p:commandLink>
                </span>
            </p:column>

            <p:column headerText="#{i18n['word.frequency']}"
                      styleClass="frequency"
                      sortBy="#{fword.frequency}"
                      rendered="#{renderFrequency}">
                #{fword.frequency}
            </p:column>

            <p:column headerText="#{i18n['word.transcription']}"
                      styleClass="transcription">
                <ui:include src="/ui/common/transcriptions.xhtml">
                    <ui:param name="word" value="#{fword}"/>
                </ui:include>
            </p:column>

            <p:column headerText="#{i18n['word.translation']}"
                      styleClass="translation">
                <ui:include src="/ui/common/translations.xhtml">
                    <ui:param name="word" value="#{fword}"/>
                </ui:include>
            </p:column>
        </p:dataTable>
    </p:outputPanel>
</ui:composition>