vocabber-ui/src/main/java/kz/vocabber/ui/TemplateBean.java
package kz.vocabber.ui;

import kz.vocabber.api.UserService;
import kz.vocabber.api.dto.UserDTO;
import kz.vocabber.impl.users.UserRole;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;

/**
 * @author Talgat_Abdulin
 */
@Component
public class TemplateBean {
    @Resource
    private UserService userService;

    public boolean isLoginRendered() {
        return userService.getCurrentUser().getRole() == UserRole.ROLE_ANONYMOUS;
    }
    
    public UserDTO getUser() {
        return userService.getCurrentUser();
    }
}

vocabber-ui/src/main/java/kz/vocabber/ui/menu/MenuBean.java
package kz.vocabber.ui.menu;

import kz.vocabber.api.UserService;
import kz.vocabber.impl.users.UserRole;
import kz.vocabber.ui.service.Url;
import kz.vocabber.ui.service.UrlService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.util.Arrays;
import java.util.List;

/**
 * @author tabdulin
 */
// TODO: refactor - remove
@Component
@Scope("view")
public class MenuBean {
    private static final Logger logger = LoggerFactory.getLogger(MenuBean.class);

    @Resource
    private UrlService urlService;
    @Resource
    private UserService userService;
    
    public boolean renderUploads() {
        return userService.getCurrentUser().getRole() == UserRole.ROLE_USER;
    }

    public List<MenuItem> getMenuItems() {
        return Arrays.asList(MenuItem.values());
    }

    public MenuItem getActive() {
        Url current = urlService.getCurrent();
        for (MenuItem item : MenuItem.values()) {
            if (item.getUrl() == current) {
                return item;
            }
        }

        return null;
    }
}

vocabber-ui/src/main/webapp/css/templates/equivalency/equivalency.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

<f:view contentType="text/html">
    <h:head>
        <f:facet name="last">
            <link rel="shortcut icon" href="#{request.contextPath}/css/templates/equivalency/images/stack_of_books.ico"/>
            <link href="#{request.contextPath}/css/templates/equivalency/style.css" rel="stylesheet"/>

            <link href="#{request.contextPath}/css/common.css" rel="stylesheet"/>
            <script src="http://loginza.ru/js/widget.js" type="text/javascript"></script>

            <ui:insert name="head"></ui:insert>

            <ui:include src="/ui/common/ga.xhtml"/>
        </f:facet>
    </h:head>
    <h:body>
        <div id="wrapper">
            <div id="header">
                <div class="header-up">
                    <div class="logo">
                        <div class="icon">
                            <a href="#{request.contextPath}/">
                                <img src="#{request.contextPath}/css/templates/equivalency/images/stack_of_books.png"
                                     alt="#{i18n['page.main.title']}"/>
                            </a>
                        </div>

                        <h1><a href="#{request.contextPath}/">#{i18n['page.main.title']}</a></h1>
                        <p>#{i18n['page.main.subtitle']}</p>
                    </div>

                    <p:outputPanel styleClass="auth" layout="block"
                                   rendered="#{templateBean.loginRendered}">
                        <a href="https://loginza.ru/api/widget?token_url=${maven.vocabber.url}%2Fj_spring_security_check&amp;providers_set=vkontakte,facebook,google,yandex,mailru,twitter&amp;lang=ru"
                           class="loginza link login"
                           title="#{i18n['auth.link.login.title']}">
                            #{i18n['auth.link.login']}
                        </a>
                    </p:outputPanel>
                    <p:outputPanel styleClass="auth" layout="block"
                                   rendered="#{not templateBean.loginRendered}">
                        <span class="welcome">#{i18n['auth.welcome']}, <span class="user">#{templateBean.user.name}</span></span>
                        <a href="#{request.contextPath}/logout" class="link logout">
                            #{i18n['auth.link.logout']}
                        </a>
                    </p:outputPanel>
                </div>

                <div style="clear:both;">&nbsp;</div>
                <div id="menu">
                    <!-- TODO: user  type="none" after upgrate to primefaces 3.2 -->
                    <p:dataList value="#{menuBean.menuItems}" var="item"
                            styleClass="#{menuBean.renderUploads() ? '' : 'no-uploads'}">
                        <li class="#{item}
                                   #{menuBean.active eq item ? 'current_page_item' : ''}">
                            <a href="#{request.contextPath}/ui/#{item.url.url}">
                                #{i18n[item.code]}
                            </a>
                        </li>
                    </p:dataList>
                </div>
            </div>
            <!-- end #header -->
            <div id="page">
                <div id="page-bgtop">
                    <div id="page-bgbtm">
                        <div id="content">
                            <h:form id="messages">
                                <p:growl id="growl" showDetail="false" globalOnly="true"/>
                            </h:form>
                            <ui:insert name="content"></ui:insert>
                        </div>
                        <div style="clear: both;">&nbsp;</div>
                    </div>
                </div>
            </div>
            <!-- end #page -->
        </div>
        <div id="footer">
            <p>Copyright (c) 2011 Vocabber.com. All rights reserved.</p>
        </div>
        <!-- end #footer -->

        <ui:include src="/ui/common/feedback.xhtml"/>
    </h:body>
</f:view>
</html>